### ISSUE TITLE
1-2 hover

### ISSUE THREAD

**Issue by kzfm** [cbi-society/cheminfotutorial1023#16]
3.3でマウスオーバーで構造が出ない場合がある

このあたり？
https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tooltips.html

**Comment by iwatobipen** [comment]
3.3で再現することを確認しています。
environmentは3．2に固定しましたが、当日３．３の方がいる場合は
output_notebook()
を無効化し、別のページに出力すればホバーが機能するのでそのように対応します。
