### ISSUE TITLE
Windowsでvsflowが動かない

### ISSUE THREAD

**Issue by kzfm** [cbi-society/cheminfotutorial1023#18]
シェバンの問題？
https://github.com/czodrowskilab/VSFlow/blob/master/vsflow

https://qiita.com/SAITO_Keita/items/82c0434ec68d1eaf57dc

**Comment by iwatobipen** [comment]
昨日のエラーをWin環境で確認しました。
上のリンクのvsflowをインストール後Linux/MacはCLIとして呼べるようになりますが、Winはそこがうまく動作していません。
対応策として上記のファイルを03ディレクトリに配置し、コマンドもWinの方用に書き換えたものを追記します。

**Comment by kzfm** [comment]
We performed the searches on up-to-date standard notebook hardware, namely a 12th Gen Intel(R) Core(TM) i7-12700 H with 2.70 GHz and 20 cores and 32GB RAM running Windows 11.

https://jcheminf.biomedcentral.com/articles/10.1186/s13321-023-00703-1
