### ISSUE TITLE
1-1 の演習

### ISSUE THREAD

**Issue by kzfm** [cbi-society/cheminfotutorial1023#7]
「ここまでのフローをベースに分子の正規化を行う関数を作成してください。」とあるのだけど、どういうフローにしないといけないかを明示しないとコードを書けないと思います。
1-1は全体の流れが見えにくいように思います。

**Comment by kzfm** [comment]
@iwatobipen  1_1ブランチを作って少し修正したので確認してもらえますか？

**Comment by iwatobipen** [comment]
@kzfm 修正ありがとうございます。
確認しました。修正いただいたものでよいかと思います。

**Comment by kzfm** [comment]
mergeしたのでcloseします
